package uk.co.jeeni.siren;

public enum InputTypes {
	HIDDEN, TEXT, SEARCH, TEL, URL, EMAIL, PASSWORD, DATETIME, DATE, MONTH, WEEK, TIME, DATETIME_LOCAL, NUMBER, RANGE, COLOR, CHECKBOX, RADIO, FILE, SUBMIT, IMAGE, RESET, BUTTON;
}
